### ISSUE TITLE
add a thing to delete messages from the bot or other users

### ISSUE THREAD

**Issue by whatsadev** [SebOuellette/Discord-LiveBot#51]
title

**Comment by dcrime** [comment]
The option to delete messages should come in one of the updates soon, the main dev of this project is making my code better whenever he has time which isn't really that often so for now even my version of the project and suggestions are on hold but if you really want to delete messages you can use [my fork of the project](https://github.com/dcrime/Discord-LiveBot) and join the [discord server](https://discord.gg/TMUc8Bs) to stay updated and ask any question or add suggestions, it's preferred to ask questions there instead of making issues about it.

**Comment by dcrime** [comment]
There's currently a plugin that does exactly what you want on the server so you can close this issue, it will be added in one of the future updates
